### ISSUE TITLE
Lidarr

### ISSUE THREAD

**Issue by Zamana** [Thefrank/freebsd-port-sooners#1]
Hi!

This is not an issue, but actually a request/question (I didn't find other way to get in contact; sorry).

I was able to get Radarr v3 running in my current TrueNAS CORE installation with the package (txz) that you provided. Thank you so much!!!

Is it possible to do the same for Lidarr, please? Or at least show me how I can do it?

Thanks.
Regards.

**Comment by Thefrank** [comment]
So, I have been putting off `lidarr` for a few reasons:
- `lidarr` currently has a `mono` version that is still current-ish: https://www.freshports.org/net-p2p/lidarr/
- There is no published dotnet version for FreeBSD: https://github.com/Lidarr/Lidarr/releases
- Using the ports system to download from things like Azure DevOP is not simple (https://dev.azure.com/Lidarr/Lidarr/_build?definitionId=1&_a=summary). It is doable but makes long-term support a pain.
- There was no demand (until now).

I still want to wait until there is a more stable version of `lidarr` before making a package for it.
I will leave this open as a reminder to myself and thanks for letting me know that there is some demand for it :)

**Comment by Zamana** [comment]
Hi!

Thanks for the kindly reply.

In fact, after your reply, I was able to install the pkg version of lidarr (0.7.2.1878) and then upgrade to the latest and greatest version (0.8.1.2135) from the webui (Settings->Update).

Thank you!

**Comment by Thefrank** [comment]
@Zamana 
https://www.freshports.org/net-p2p/lidarr/ 
maintainer is now the same for all *arr's and now uses dotnet :)
