### ISSUE TITLE
Wrong commands in instructions

### ISSUE THREAD

**Issue by swannie-eire** [Thefrank/freebsd-port-sooners#10]
I followed the instructions in https://github.com/Thefrank/freebsd-port-sooners/blob/main/Prowlarr_Installation_TrueNAS_GUI.md but i think they are wrong after installing prowlarrdotnet it says to start run ```prowlarrdotnet_enable="TRUE"``` and then ```service prowlarrdotnet start``` your instructions state ```prowlarr_enable="TRUE"``` and then ```service prowlarr start```

When i try to start with your command i get the error 
```
prowlarr does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
```

It starts successfully with the command below and prowlarr seems to start from the logs but I still cant get it to load. The port appears to be up but nothing will load in the browser. I have _allow_raw_sockets_ and _allow_mlock_ enabled but still no luck.
```service prowlarrdotnet start```

https://imgur.com/xaBL5Gk

**Comment by Thefrank** [comment]
oops! I forgot to update the guide after I updated the binary naming but its updated now. The naming inside the package is done automatically. The guide is done manually.

As for the other issue: can you post the log (or part of it)?

**Comment by swannie-eire** [comment]
i just tested it there again and it appears to be working now. here were the commands i ran. It does not appear to be as customisable as jackett as i can find where the indexer files are stored to create my own so im sticking with jackett. thanks for the guide.

`pw user add prowlarr -c prowlarr -u 349 -d /nonexistent -s /usr/bin/nologin
fetch https://github.com/Thefrank/freebsd-port-sooners/releases/download/20211015/prowlarrdotnet-0.1.1.978.pkg
pkg install prowlarrdotnet-0.1.1.978.pkg
sysrc prowlarrdotnet_enable=TRUE
service prowlarrdotnet start
tail -f /var/db/prowlarrdotnet/logs/prowlarr.txt
service prowlarrdotnet restart
sysrc prowlarrdotnet_user="prowlarr"
sysrc prowlarrdotnet_group="prowlarr"
sysrc prowlarrdotnet_data_dir="/usr/local/prowlarrdotnet/"
/usr/local/prowlarrdotnet/Prowlarr --data=/usr/local/prowlarrdotnet/ --nobrowser
`
