### ISSUE TITLE
Ombi

### ISSUE THREAD

**Issue by Thefrank** [Thefrank/freebsd-port-sooners#11]
poking @Sicer

Looks like it is on dotNET6 so I will take a look at it over the weekend

**Comment by Thefrank** [comment]
Same issue as dotNET5 it seems. Posted about it here https://github.com/dotnet/runtime/issues/14537#issuecomment-974909269

**Comment by Thefrank** [comment]
@Sicer
Please give this a shot: https://github.com/Thefrank/freebsd-port-sooners/releases/tag/20211129
the pkg requires `pkg` >= 1.17.0

**Comment by Sicer** [comment]
Thank you very much for the work, any guide on how to install it?

**Comment by Thefrank** [comment]
the .pkg installs everything it needs. just download it into a jail, `pkg install`, `sysrc` the required/optional variables (the install message explains them, then start the service :)

Once a few more people confirm everything is working OK I will make a guide for those less familiar with FreeBSD's CLI (e.g., TrueNAS/FreeNAS users)

**Comment by Sicer** [comment]
> the .pkg installs everything it needs. just download it into a jail, `pkg install`, `sysrc` the required/optional variables (the install message explains them, then start the service :)
> 
> Once a few more people confirm everything is working OK I will make a guide for those less familiar with FreeBSD's CLI (e.g., TrueNAS/FreeNAS users)

thanks, I'll wait for someone to try it and make the guide to trueNAS

**Comment by Thefrank** [comment]
@Sicer I added an initial guide for Ombi https://github.com/Thefrank/freebsd-port-sooners/blob/main/Ombi_Installation_TrueNAS_GUI.md

**Comment by Thefrank** [comment]
Closing. Looks like everything functional with it. Reopen or make a new ticket if you have issues :)

**Comment by SebastianChudoba** [comment]
Ombi is now on v4.22.5. Any chance to get it updated?

**Comment by Thefrank** [comment]
@SebastianChudoba in the future please open a new ticket. Github doesn't always push replies to closed issues to my email.

![image](https://user-images.githubusercontent.com/1910378/188254218-5bc67116-803f-4d35-8c53-e14b131f534e.png)

Will be going up shortly. Default GID/UID changed to 363 as 362 is now taken by Readarr

**Comment by SebastianChudoba** [comment]
Ok, will do. Thanks a lot!
