### ISSUE TITLE
Jacket version bump

### ISSUE THREAD

**Issue by Adubzzy** [Thefrank/freebsd-port-sooners#14]
Hi Frank,

Jacket was bumped up to a new major version, believe it is v.20.576. Can you release a new jacketdotnet build if you have time?

**Comment by Thefrank** [comment]
Should be able to get that updated this weekend. Thanks for letting me know!

**Comment by Thefrank** [comment]
@Adubzzy 
https://github.com/Thefrank/freebsd-port-sooners/releases/tag/20220220

works fine locally, reopen if there are issues
