### ISSUE TITLE
ombi with multiple mysql databases

### ISSUE THREAD

**Issue by Sicer** [Thefrank/freebsd-port-sooners#15]
I have read that you can change the sqllite database for multiple mysql, would it be possible to add some pkg that would configure all this in a more simple way?

**Comment by Thefrank** [comment]
While the ports system supports building/packaging very complex things its generally not a good idea to have something like that  create databases that need users and passwords with them.

There might exist scripts to set those up for ombi and should work under FreeBSD but generally something like database setup should be done by hand so everything can be configured to your usage and security needs.

**Comment by Sicer** [comment]
> While the ports system supports building/packaging very complex things its generally not a good idea to have something like that create databases that need users and passwords with them.
> 
> There might exist scripts to set those up for ombi and should work under FreeBSD but generally something like database setup should be done by hand so everything can be configured to your usage and security needs.

and any manual to install it? I have not been able to ride it in thunder

**Comment by Thefrank** [comment]
I found this guide which covers your usage case: https://docs.ombi.app/info/alternate-databases/

I don't have the time right now to try and set it up my self but I don't see any reason why it would not work under FreeBSD

**Comment by Thefrank** [comment]
Over 90 days. Closing
