### ISSUE TITLE
Ombi installation

### ISSUE THREAD

**Issue by willart7401** [Thefrank/freebsd-port-sooners#16]
Hello, I'm sorry to open an issue for this but I can't install the latest version of Ombi.
So, I try to install the old ombi-4.25.0.pkg version but when all start, there is nothing on IP:5000 and no error...
What can I do ?

**Comment by Thefrank** [comment]
if you are installing it in a jail make sure that unprivileged mlock is enabled. Most jail managers will list this as  `allow.mlock`

**Comment by willart7401** [comment]
Yeah I have enabled it.
For the tar.gz file, how to install it ? Because it's not a pkg file

**Comment by Thefrank** [comment]
I should have some time to make and test a full pkg before the start of next week. It looks like the last one I generated was Dec of 2021

If you don't want to wait, you can just unpack the tarball and run the program

**Comment by Thefrank** [comment]
@willart7401 
Actually a version without test failures (flaky or otherwise): https://github.com/Thefrank/freebsd-port-sooners/releases/tag/20230416

If everything works, feel free to close this

**Comment by Thefrank** [comment]
Over 90 days. Closing.
