### ISSUE TITLE
Ombi pkg install still refers to group 362

### ISSUE THREAD

**Issue by Delta-Entropy** [Thefrank/freebsd-port-sooners#17]
I get the following error when trying to install ombi-4.35.18.pkg:

pw: group `362' does not exist

+MAINFEST has the following:

${PW} useradd ombi -u 363 -g 362

I was able to get it to work by changing it to 363

**Comment by Thefrank** [comment]
`362` is taken by `Readarr` currently. I have moved both UID and GID to 363 and reuploaded the package.

Thanks for letting me know about the bug!
