### ISSUE TITLE
Powershell: can't run tmux/screen

### ISSUE THREAD

**Issue by DNS** [Thefrank/freebsd-port-sooners#19]
Version:
Freebsd 14
Konsole
[Powershell-FreeBSD-x64.v7.2.8.tar.bz2](https://github.com/Thefrank/freebsd-port-sooners/releases/download/20221219/Powershell-FreeBSD-x64.v7.2.8.tar.bz2) as default shell
`chsh -s /home/dns/Downloads/pwsh/pwsh`

![Screenshot_20231223_233644](https://github.com/Thefrank/freebsd-port-sooners/assets/37093/c601089a-e158-4f8c-ae5d-f7fc197dd9a1)

**Comment by Thefrank** [comment]
Powershell uses `bash` for many external commands.  Under Linux it uses `sh` for the login shell. Until FreeBSD 14, `sh` could not be used as a login shell so I opted for `pwsh` to use `bash` instead as it was already being used as a runtime dependency. As the build is more than 1yr old, I will need to take a look at anything that needs changes.

As long as FreeBSD sees `pwsh` as a valid shell (i.e has a `/etc/shells` entry) it should behave as one and be switched into via [chpass](https://man.freebsd.org/cgi/man.cgi?chpass(1)) if it supports usage as a login shell.

I don't have any *nix machines setup that can use a desktop environment. I should have some time after the end of the year to build a FreeBSD one with some extra parts. What other software do you have installed? `pkg info` will give a nice list of what you have installed. If it spits out too many packages then I just need to know what desktop environment and user interface you using when running Konsole under FreeBSD.  `tmux` and `screen` are also ports and not a part of the base FreeBSD OS which might complicate things for Powershell but we shall see!

**Comment by DNS** [comment]
tmux works fine when using sh/bash/csh as default shell. 
Only if powershell as default shell, tmux will be terminated early. 
I already add pwsh path to /etc/shells.

I use KDE5, konsole, htop, micro, pwsh, 7z.
csh/sh/pwsh seems work well with konsole, except when using bash as default shell, the konsole tab not exiting immediately (delay 1.5-2 seconds).

**Comment by DNS** [comment]
After some investigation, it seems tmux only fail to launch pwsh (others shells csh/sh/bash work fine).
```
PS /home/dns> cat /home/dns/.tmux.conf
set -g default-shell /home/dns/Downloads/pwsh/pwsh
```

So it's not about the default FreeBSD shells. 
When tmux creating new session, it just fail to launch pwsh.

**Comment by DNS** [comment]
Related to this bug: https://github.com/Thefrank/freebsd-port-sooners/issues/18#issuecomment-1868503352
