### ISSUE TITLE
import plex users not working - known ombi bug

### ISSUE THREAD

**Issue by Hagya15** [Thefrank/freebsd-port-sooners#21]
import plex users is broken in the latest package. this is talked about [here](https://github.com/Ombi-app/Ombi/issues/4989).
Most importantly, tidusjar made a change that fixed it [here](https://github.com/Ombi-app/Ombi/commit/c8ad12eb5f53889609d1793ae907afd33ba6ef38), this was confirmed to resolve the issue. 

since this just changes the site plex imports the users from, is it possible for me to change something in my installation to make this work? or would this require compiling a new package?

**Comment by Thefrank** [comment]
That does not look like something that can be changed by the end user.
I will try and get a build of Ombi out before the weekend. The one here is rather old

**Comment by Hagya15** [comment]
Great, i want to point out that this fix is only in the development branch yet. Maybe you would have to change those lines manually if you were to port the latest stable release

**Comment by Thefrank** [comment]
pull/5115 just landed and moves everything to dotNET8. If this is not a part of tag by the weekend I will build from newest preview tag

**Comment by Thefrank** [comment]
@Hagya15 

https://github.com/Thefrank/freebsd-port-sooners/releases/tag/20240515

it builds with no test failures, packages, and starts without errors. Let me know if this version fixes your issue.

**Comment by Hagya15** [comment]
works like a charm, thank you!
