### ISSUE TITLE
Readarr Support?

### ISSUE THREAD

**Issue by kmcbride3** [Thefrank/freebsd-port-sooners#3]
Any chance of supporting a Readarr build for FreeBSD/TrueNAS, or are you holding off until it leaves beta?

**Comment by Thefrank** [comment]
Similar to why there is no `lidarr` package/port

Once it leaves beta I will make a package for it

**Comment by kmcbride3** [comment]
That's sort of what I figured. Thanks for the quick response!

**Comment by spacecabbie** [comment]
> Similar to why there is no `lidarr` package/port
> 
> Once it leaves beta I will make a package for it

You might wana tell the readarr guys that they point to you repo :)
https://readarr.com/#download

**Comment by Thefrank** [comment]
It looks like that info was copied over from `Radarr` as it links to the Radarr Guide, the binary link returns a 404 for `develop` and `master`, it looks like `Readarr` still only has a `nightly` branch

**Comment by Thefrank** [comment]
@kmcbride3 @spacecabbie https://www.freshports.org/net-p2p/readarr/

It's actually in ports and should be in pkg in a week or less :)
