### ISSUE TITLE
prowlarr fails to download, authentication error

### ISSUE THREAD

**Issue by mysticpete** [Thefrank/freebsd-port-sooners#5]
![Screen Shot 2021-09-28 at 9 28 55 pm](https://user-images.githubusercontent.com/2877294/135078710-f9eed6bc-4826-4e41-aabf-0d020304b2ee.png)

Upload fails due to "certificate verification failed", see attached screen shot.

**Comment by Thefrank** [comment]
try `pkg install ca-root-nss`

**Comment by Thefrank** [comment]
@mysticpete did that work out for you?

**Comment by Thefrank** [comment]
Closing. Over 60 days with no response + `prowlarr` is now in ports
