### ISSUE TITLE
Jacketdotnet major version update

### ISSUE THREAD

**Issue by Adubzzy** [Thefrank/freebsd-port-sooners#9]
Jackett was update to v19... Would you be able to update your dotnet version?

**Comment by Thefrank** [comment]
sure! I will take a look at it over the weekend. hopefully not too much has changed

**Comment by Thefrank** [comment]
Nothing major appears to have changed. Built and runs fine: https://github.com/Thefrank/freebsd-port-sooners/releases/tag/20211111

Enjoy!

If there are no issues with it for you, feel free to close this :)

**Comment by Adubzzy** [comment]
Works great!... Thank you.
